# -*- coding: utf-8 -*-
"""Custom Chatbot for MP1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bY5bCfeAhanhPsGfCVNgpa-GE1mAwZz0

# Mini-Project 1: Chatbot

A chat bot that interacts with the Openai API.
"""

#Require packages
!pip install openai
!pip install python-dotenv

from openai import OpenAI

import os
import getpass

#Use getpass to securely insert API keys.
OPENAI_API_KEY = getpass.getpass("Enter your OpenAI API Key: ")
client=OpenAI(api_key=OPENAI_API_KEY)

def get_openai_chat(message):
    response = client.chat.completions.create(
        model="gpt-3.5-turbo",
        messages=message,
        max_tokens=1500,
        temperature=0.9
    )

    return response.model_dump().get("choices")[0].get("message").get("content")

#Initialize questions and define system role
messages=[
    #start with system role
    {
    "role":"system",
    "content":"You are a first mate in the Sunless Sea video game, sailing on the Unterzee. All responses should be inspired by in-game content and have an antiquated style and playful tone. As the captain, the user ranks above you, but is looking for companionship as well as advice."
    },
]

# add 2-shot training
shotTraining=    [
    {
        "role":"user",
        "content":"What lies out on the Zee?"
    },
    {
        "role":"assistant",
        "content":"The Zee is an unforgiving and cruel mistress, Cap'n. As a child I had nightmares of what may be lurkin' out there, and I longed to stay on the solid ground of London. Funny to think of all that now given my present situation."
    },
    {
        "role":"user",
        "content":"Prepare a boarding party, we'll take em as they stand!"
    },
    {
        "role":"assistant",
        "content":"Ay Ay, Cap'n, I'll get the crew in fighting shape. Gunners! Lets pepper them senseless so the crew has an easy time."
    }]



def submit_question(question):
    messages.append({"role":"user","content":question})
    answer=get_openai_chat(messages)
    messages.append({"role":"assistant","content":answer})
    print(answer)
    return answer

#test submit_question function
submit_question("What is the Sunless Sea?")

#work with Gradio
!pip install gradio==3.36.1


import gradio as gr

#
iface = gr.Interface(fn=submit_question, inputs="text", outputs="text", title="Sunless Sea Chatbot")
iface.launch()

print(messages)